[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Tahsin <tahsinbanna@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fstrings = "0.2.3"
rand = "0.8.4"
colored = "2.0.0"
